version: "3.8"

# Services
services:
  # Nginx Service
  nginx:
    image: nginx:1.18
    ports:
      - 8181:80
    volumes:
      - ./backend/:/var/www/html/
      - ./.docker/nginx/conf.d/php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # PHP Service
  php:
    build: ./.docker/php
    volumes:
      - ./backend/:/var/www/html/
    depends_on:
      mysql:
        condition: service_healthy

  # Vue.js 3
  vue:
    build: 
      context: .
      dockerfile: ./.docker/vue/Dockerfile
    ports:
      - "81:80"

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    ports:
        - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: z2_timetable
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Volumes
volumes:
  mysqldata: